#include <xc.h>
#include "0x2a002a.h"

void GPIO_and_PPS_init(void)
{
    __builtin_disable_interrupts();

    SYSKEY = 0x0;
    SYSKEY = 0xAA996655;
    SYSKEY = 0x556699AA;
    CFGCONbits.IOLOCK = 0;
    SYSKEY = 0x33333333;

    // Main encoder A
    COD_A_ANALOG = DIGITAL_PIN;
    COD_A_GPIO = GPIO_INPUT;
    PPS_COD_A;

    // Main encoder B
    COD_B_ANALOG = DIGITAL_PIN;
    COD_B_GPIO = GPIO_INPUT;
    PPS_COD_B;

    // SPI1
    SPI1_CS0_GPIO = GPIO_OUTPUT;
    CS_MCP_LCD = CS_LINE_UP;
    SPI1_CS1_GPIO = GPIO_OUTPUT;
    CS_MCP_ENCODERS = CS_LINE_UP;
    SPI1_CS2_GPIO = GPIO_OUTPUT;
    CS_EEPROM = CS_LINE_UP;
    SPI1_CS3_GPIO = GPIO_OUTPUT;
    CS_SD = CS_LINE_UP;
    SPI1_CS2_ANALOG = DIGITAL_PIN;
    SPI1_CS3_ANALOG = DIGITAL_PIN;
    SDI1_ANALOG = DIGITAL_PIN;
    PPS_SDI1;
    SDO1_ANALOG = DIGITAL_PIN;
    PPS_SDO1;
    MIDI_ANALOG = DIGITAL_PIN;
    PPS_MIDI;
    MCP_ENC_A_ANALOG = DIGITAL_PIN;
    COD_MCP_A_GPIO = GPIO_INPUT;
    PPS_MCP_ENC_A;
    MCP_ENC_B_ANALOG = DIGITAL_PIN;
    COD_MCP_B_GPIO = GPIO_INPUT;
    PPS_MCP_ENC_B;

    SYSKEY = 0x0;
    SYSKEY = 0xAA996655;
    SYSKEY = 0x556699AA;
    CFGCONbits.IOLOCK = 1;
    SYSKEY = 0x33333333;
}

void TIMER_init(void)
{
    TIMER2_STOP_AND_RESET;
    TIMER2_VALUE = 0;
    TIMER2_PRESCALE = TIMER_PRESCALE_256;

    TIMER3_STOP_AND_RESET;
    TIMER3_VALUE = 0;
    TIMER3_PRESCALE = TIMER_PRESCALE_256;
    TIMER3_PERIOD = 0xFFFF;

    TIMER4_STOP_AND_RESET;
    TIMER4_VALUE = 0;
    TIMER4_PRESCALE = TIMER_PRESCALE_256;
    TIMER4_PERIOD = 60000;
//	TIMER4_PERIOD = ONE_MILLISECOND / 64 * SCREEN_DURATION_MS - 1;

    TIMER5_STOP_AND_RESET;
    TIMER5_VALUE = 0;
    TIMER5_PRESCALE = TIMER_PRESCALE_4;
    TIMER5_PERIOD = 64 * FREQUENCY / (8000 / BUTTON_POLL_DELAY_MS) - 1;
}

void INT_init(void)
{
    __builtin_disable_interrupts();
    INTCONbits.MVEC = 1;

    // HT16
    HT16_INT_POLARITY = FALLING_EDGE;
    HT16_INT_FLAG_CLR;
    HT16_INT_PRIORITY = 2;
    HT16_INT_ENABLE = INT_ENABLED;

    // MAIN ENCODER
    COD_A_INT_POLARITY = RISING_EDGE;
    COD_A_INT_FLAG_CLR;
    COD_A_INT_PRIORITY = 2;
    COD_A_INT_ENABLE = INT_ENABLED;
    COD_B_INT_POLARITY = RISING_EDGE;
    COD_B_INT_FLAG_CLR;
    COD_B_INT_PRIORITY = 2;
    COD_B_INT_ENABLE = INT_ENABLED;

    // TIMERS
    TIMER2_INT_FLAG_CLR;
    TIMER2_INT_PRIORITY = 3;
    TIMER2_INT_ENABLE = INT_ENABLED;
    TIMER3_INT_FLAG_CLR;
    TIMER3_INT_PRIORITY = 1;
    TIMER3_INT_ENABLE = INT_ENABLED;
    TIMER4_INT_FLAG_CLR;
    TIMER4_INT_PRIORITY = 1;
    TIMER4_INT_ENABLE = INT_ENABLED;
    TIMER5_INT_FLAG_CLR;
    TIMER5_INT_PRIORITY = 3;
    TIMER5_INT_ENABLE = INT_ENABLED;
    // l'interruption est activee uniquement en cas de poll

    // UART
    UART1_TX_INT_FLAG_CLR;
    UART1_TX_INT_PRIORITY = 5;
    // ~UART1_TX_INT_ENABLE = INT_ENABLED;~ UART interrupt is enabled on sent messages

    //I2C1
    I2C1_INT_FLAG_CLR;
    I2C1_INT_PRIORITY = 4;
    I2C1_INT_ENABLE = 1;

    //SPI1
    SPI1_INT_FLAGS_CLR_RX;
    SPI1_INT_FLAGS_CLR_TX;
    SPI1_INT_PRIORITIES = 4;
    //PERSISTANT !!!!!!!!!!!!!!!!!!!!!!!!!!!
    SPI1_RECEIVE_ENABLE = INT_DISABLED;
    SPI1_TRANSFER_ENABLE = INT_DISABLED;

    // MCP encoders interrupts
    //         COD_MCP_INT_POLARITY = FALLING_EDGE;
    //         COD_MCP_INT_FLAG = 0; // Reset the flag
    //         IPC1bits.INT1IP = 3; // Set priority
    //         IEC0bits.INT1IE = 1; // Enable interrupt

    INTCONbits.INT3EP = FALLING_EDGE;
    IFS0bits.INT3IF = 0; // Reset the flag
    IPC3bits.INT3IP = 2; // Set priority
    IEC0bits.INT3IE = 1; // Enable interrupt

    __builtin_enable_interrupts();
}