SOURCES = bpm.c
SOURCES += config.c
SOURCES += encoders_driver.c
SOURCES += HT16_keys_driver.c
SOURCES += HT16_leds_driver.c
SOURCES += I2C_driver.c
SOURCES += init.c
SOURCES += input_handler.c
SOURCES += LCD_driver.c
SOURCES += LCD_templates.c
SOURCES += main.c
SOURCES += mappings.c
SOURCES += MIDI.c
SOURCES += notes.c
SOURCES += output_handler.c
SOURCES += SDCARD_driver.c
SOURCES += sequencer.c
SOURCES += simulation.c
SOURCES += SPI_driver.c
SOURCES += timers_driver.c
SOURCES += UART_driver.c

all:
	gcc -o  output -DSIMULATION ${SOURCES}
