#include "0x2a002a.h"

u8 encoder_midi_cc[8] =
{
    MC_GP_CONTROLLER_1,
    MC_GP_CONTROLLER_2,
    MC_GP_CONTROLLER_3,
    MC_GP_CONTROLLER_4,
    MC_GP_CONTROLLER_5,
    MC_GP_CONTROLLER_6,
    MC_GP_CONTROLLER_7,
    MC_GP_CONTROLLER_8,
};